language: rust

cache: cargo

jobs:
  include:
    - stage: build
      rust: stable
      os: osx
      script:
        - cargo build --verbose
    - stage: build
      rust: stable
      os: linux
      script:
        - cargo build --verbose
    - stage: build
      rust: beta
      os: osx
      script:
        - cargo build --verbose
    - stage: build
      rust: beta
      os: linux
      script:
        - cargo build --verbose
    - stage: build
      rust: nightly
      os: osx
      script:
        - cargo build --verbose
        - cargo test --verbose
    - stage: build
      rust: nightly
      os: linux
      script:
        - cargo build --verbose
    - stage: test
      rust: nightly
      os: osx
      script:
        - cargo test --verbose
    - stage: test
      rust: nightly
      os: linux
      script:
        - cargo test --verbose
